name: LightstoneEngine
main: protocolsupport.ProtocolSupport
version: mcpe-latest-july2020
authors:
- _Shevchik_
- 7kasper
- MrPowerGamerBR
- gdude2002
- connor557
load: STARTUP
commands:
  protocolsupport:
    description: All ProtocolSupport commands
    aliases: ps
    usage: '/protocolsupport help'
